### PR TITLE
[FIZZ-83] Sample output files

### PR DESCRIPTION
**Pull request by stephenfuqua**
I couldn't figure out what the `LMSGrade` model represents, as distinct from the `Grade` field on the `AssignmentSubmission` model, so there is no sample of this model.

### CODE REVIEW

**Review by bradbanister — APPROVED** [review]
LGTM

**Comment by stephenfuqua** [comment]
> I couldn't figure out what the `LMSGrade` model represents, as distinct from the `Grade` field on the `AssignmentSubmission` model, so there is no sample of this model.

@ggaronzik explained after standup that some of these systems allow a grade to be recorded directly on the enrollment, rather than only on the assignment.

**Comment by stephenfuqua** [comment]
@ggaronzik can you take one more look  now that I've made modifications based on your review comments in Jira?

**Comment by stephenfuqua** [comment]
All review comments have been addressed. I'm going to merge this. We can always modify again later if we find required tweaks.

**Pull request merged**
